# Generated by Django 4.2.16 on 2025-11-10 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import orders.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_code', models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='رقم الطلب')),
                ('department', models.CharField(blank=True, max_length=255, verbose_name='القسم/الجهة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending', 'بانتظار المراجعة'), ('in_review', 'قيد الاعتماد'), ('approved', 'تم الاعتماد'), ('in_production', 'قيد الإنتاج'), ('ready', 'جاهز للتسليم'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة الحالية')),
                ('priority', models.CharField(choices=[('low', 'عادية'), ('medium', 'متوسطة'), ('high', 'عاجلة')], default='medium', max_length=20, verbose_name='الأولوية')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='يحتاج اعتماد')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_approvals', to=settings.AUTH_USER_MODEL, verbose_name='المعتمد الحالي')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_orders', to=settings.AUTH_USER_MODEL, verbose_name='مقدم الطلب')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalog.service', verbose_name='الخدمة')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'الطلبات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending', 'بانتظار المراجعة'), ('in_review', 'قيد الاعتماد'), ('approved', 'تم الاعتماد'), ('in_production', 'قيد الإنتاج'), ('ready', 'جاهز للتسليم'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التغيير')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'سجل حالة',
                'verbose_name_plural': 'سجل الحالات',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attachment_type', models.CharField(choices=[('file', 'ملف'), ('link', 'رابط')], max_length=10, verbose_name='نوع المرفق')),
                ('file', models.FileField(blank=True, upload_to=orders.models.order_attachment_upload_path, verbose_name='ملف')),
                ('link_url', models.URLField(blank=True, verbose_name='رابط خارجي')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='الاسم الظاهر')),
                ('size_bytes', models.PositiveIntegerField(blank=True, null=True, verbose_name='الحجم بالبايت')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='orders.order', verbose_name='الطلب')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مرفق طلب',
                'verbose_name_plural': 'مرفقات الطلبات',
            },
        ),
        migrations.CreateModel(
            name='OrderApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step', models.PositiveIntegerField(default=1, verbose_name='خطوة الاعتماد')),
                ('decision', models.CharField(choices=[('pending', 'بانتظار القرار'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='القرار')),
                ('comment', models.TextField(blank=True, verbose_name='ملاحظات المعتمد')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ القرار')),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to=settings.AUTH_USER_MODEL, verbose_name='المعتمد')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='orders.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'اعتماد طلب',
                'verbose_name_plural': 'اعتمادات الطلبات',
                'ordering': ['order', 'step'],
            },
        ),
        migrations.CreateModel(
            name='OrderFieldValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.JSONField(blank=True, null=True, verbose_name='القيمة')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_values', to='catalog.servicefield', verbose_name='الحقل')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='orders.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'قيمة حقل',
                'verbose_name_plural': 'قيم الحقول',
                'unique_together': {('order', 'field')},
            },
        ),
    ]
