# Generated by Django 4.2.11 on 2025-12-22 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='entity',
            field=models.ForeignKey(blank=True, help_text='الجهة المسجلة عليها الطلب (تُسجل آلياً من جهة المستخدم)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='entities.entity', verbose_name='الجهة'),
        ),
    ]
