# Generated by Django 4.2.11 on 2025-12-22 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import orders.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_order_entity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_code', models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='رقم الطلب')),
                ('print_type', models.CharField(choices=[('books', 'كتب'), ('business_cards', 'كروت شخصية'), ('banners', 'بانرات'), ('posters', 'بوسترات'), ('brochures', 'بروشورات'), ('flyers', 'منشورات'), ('letterheads', 'أوراق رسمية'), ('envelopes', 'ظروف'), ('labels', 'ملصقات'), ('stickers', 'ستيكر'), ('certificates', 'شهادات'), ('forms', 'نماذج'), ('other', 'أخرى')], max_length=30, verbose_name='نوع الطباعة')),
                ('production_dept', models.CharField(choices=[('offset', 'أوفست'), ('digital', 'ديجيتال'), ('gto', 'GTO')], max_length=20, verbose_name='قسم الإنتاج')),
                ('size', models.CharField(choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('A6', 'A6'), ('A7', 'A7'), ('custom', 'مخصص')], max_length=10, verbose_name='الحجم')),
                ('custom_size', models.CharField(blank=True, max_length=100, verbose_name='الحجم المخصص')),
                ('paper_type', models.CharField(choices=[('normal', 'عادي'), ('coated', 'كوشيه'), ('cardboard', 'كرتون'), ('transparent', 'شفاف'), ('sticker', 'ستيكر')], max_length=20, verbose_name='نوع الورق')),
                ('paper_weight', models.PositiveIntegerField(help_text='70g - 350g', verbose_name='وزن الورق (جرام)')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية المطلوبة')),
                ('actual_quantity', models.PositiveIntegerField(blank=True, help_text='يُدخلها موظف القسم عند الإكمال (لخصم المخزون)', null=True, verbose_name='الكمية الفعلية المنفذة')),
                ('sides', models.PositiveIntegerField(default=1, help_text='1 = وجه واحد، 2 = وجهين', verbose_name='عدد الأوجه')),
                ('pages', models.PositiveIntegerField(default=1, help_text='عدد الصفحات في كل وجه', verbose_name='عدد الصفحات')),
                ('delivery_method', models.CharField(choices=[('self_pickup', 'استلام ذاتي'), ('delivery', 'توصيل'), ('delivery_install', 'توصيل + تركيب')], max_length=20, verbose_name='طريقة التسليم')),
                ('status', models.CharField(choices=[('pending_review', 'بانتظار المراجعة'), ('in_production', 'قيد الإنتاج'), ('pending_confirm', 'بانتظار التأكيد'), ('in_warehouse', 'في المستودع'), ('delivery_scheduled', 'تم حجز التسليم'), ('archived', 'مؤرشف'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي')], default='pending_review', max_length=20, verbose_name='الحالة')),
                ('priority', models.CharField(choices=[('normal', 'عادي'), ('urgent', 'عاجل'), ('emergency', 'طارئ')], default='normal', max_length=20, verbose_name='الأولوية')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التأكيد')),
                ('confirmation_deadline', models.DateTimeField(blank=True, null=True, verbose_name='موعد انتهاء التأكيد')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ التقديم')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='print_orders', to='entities.entity', verbose_name='الجهة')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_orders', to=settings.AUTH_USER_MODEL, verbose_name='مقدم الطلب')),
            ],
            options={
                'verbose_name': 'طلب طباعة',
                'verbose_name_plural': 'طلبات الطباعة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrintAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attachment_type', models.CharField(choices=[('file', 'ملف'), ('link', 'رابط')], max_length=10, verbose_name='نوع المرفق')),
                ('file', models.FileField(blank=True, upload_to=orders.models.print_attachment_upload_path, verbose_name='ملف')),
                ('link_url', models.URLField(blank=True, verbose_name='رابط خارجي')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='الاسم الظاهر')),
                ('size_bytes', models.PositiveIntegerField(blank=True, null=True, verbose_name='الحجم بالبايت')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('print_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='orders.printorder', verbose_name='طلب الطباعة')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_print_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مرفق طلب طباعة',
                'verbose_name_plural': 'مرفقات طلبات الطباعة',
            },
        ),
        migrations.CreateModel(
            name='DesignOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_code', models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='رقم الطلب')),
                ('design_type', models.CharField(choices=[('poster', 'بوستر'), ('brochure', 'بروشور'), ('card', 'كارت'), ('certificate', 'شهادة'), ('logo', 'شعار'), ('other', 'أخرى')], max_length=20, verbose_name='نوع التصميم')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('size', models.CharField(choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('A6', 'A6'), ('custom', 'مخصص')], max_length=10, verbose_name='الحجم')),
                ('custom_size', models.CharField(blank=True, max_length=100, verbose_name='الحجم المخصص')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('priority', models.CharField(choices=[('normal', 'عادي'), ('urgent', 'عاجل'), ('emergency', 'طارئ')], default='normal', max_length=20, verbose_name='الأولوية')),
                ('status', models.CharField(choices=[('pending_review', 'بانتظار المراجعة'), ('in_design', 'قيد التصميم'), ('pending_confirm', 'بانتظار التأكيد'), ('completed', 'مكتمل'), ('suspended', 'معلق'), ('rejected', 'مرفوض'), ('returned', 'مرتجع')], default='pending_review', max_length=20, verbose_name='الحالة')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التأكيد')),
                ('confirmation_deadline', models.DateTimeField(blank=True, null=True, verbose_name='موعد انتهاء التأكيد')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ التقديم')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='design_orders', to='entities.entity', verbose_name='الجهة')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='design_orders', to=settings.AUTH_USER_MODEL, verbose_name='مقدم الطلب')),
            ],
            options={
                'verbose_name': 'طلب تصميم',
                'verbose_name_plural': 'طلبات التصميم',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attachment_type', models.CharField(choices=[('file', 'ملف'), ('link', 'رابط')], max_length=10, verbose_name='نوع المرفق')),
                ('file', models.FileField(blank=True, help_text='PDF, PNG, AI, PSD - بحد أقصى 25MB', upload_to=orders.models.design_attachment_upload_path, verbose_name='ملف')),
                ('link_url', models.URLField(blank=True, verbose_name='رابط خارجي')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='الاسم الظاهر')),
                ('size_bytes', models.PositiveIntegerField(blank=True, null=True, verbose_name='الحجم بالبايت')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('design_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='orders.designorder', verbose_name='طلب التصميم')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_design_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مرفق طلب تصميم',
                'verbose_name_plural': 'مرفقات طلبات التصميم',
            },
        ),
        migrations.AddIndex(
            model_name='printorder',
            index=models.Index(fields=['status', 'priority'], name='orders_prin_status_ad3980_idx'),
        ),
        migrations.AddIndex(
            model_name='printorder',
            index=models.Index(fields=['production_dept', 'status'], name='orders_prin_product_c3cc9e_idx'),
        ),
        migrations.AddIndex(
            model_name='printorder',
            index=models.Index(fields=['confirmation_deadline'], name='orders_prin_confirm_37e6fb_idx'),
        ),
        migrations.AddIndex(
            model_name='designorder',
            index=models.Index(fields=['status', 'priority'], name='orders_desi_status_5715db_idx'),
        ),
        migrations.AddIndex(
            model_name='designorder',
            index=models.Index(fields=['confirmation_deadline'], name='orders_desi_confirm_7e1431_idx'),
        ),
    ]
