# Generated by Django 4.2.11 on 2025-12-22 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid
import visits.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True, verbose_name='التاريخ')),
                ('is_blocked', models.BooleanField(default=False, help_text='صيانة، إجازات، إلخ', verbose_name='محجوز بالكامل')),
                ('blocked_reason', models.CharField(blank=True, max_length=255, verbose_name='سبب الحجب')),
                ('available_slots', models.JSONField(default=list, help_text="قائمة بأوقات المواعيد المتاحة (مثل: ['09:00', '10:00', '11:00'])", verbose_name='المواعيد المتاحة')),
                ('visit_type_restriction', models.CharField(blank=True, choices=[('internal', 'زيارة داخلية'), ('external', 'زيارة خارجية')], help_text='تخصيص اليوم لنوع معين من الزيارات', max_length=20, null=True, verbose_name='تقييد نوع الزيارة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'جدول مواعيد',
                'verbose_name_plural': 'جداول المواعيد',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='VisitRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visit_type', models.CharField(choices=[('internal', 'زيارة داخلية'), ('external', 'زيارة خارجية')], max_length=20, verbose_name='نوع الزيارة')),
                ('purpose', models.TextField(verbose_name='الغرض من الزيارة')),
                ('requested_date', models.DateField(verbose_name='التاريخ المطلوب')),
                ('requested_time', models.TimeField(verbose_name='الوقت المطلوب')),
                ('permit_file', models.FileField(blank=True, help_text='إلزامي للزيارات الخارجية', null=True, upload_to=visits.models.visit_permit_upload_path, verbose_name='تصريح موقع ومختوم')),
                ('status', models.CharField(choices=[('pending', 'بانتظار المراجعة'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('postponed', 'مؤجل'), ('cancelled', 'ملغي'), ('completed', 'مكتمل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('manager_comment', models.TextField(blank=True, verbose_name='ملاحظات المدير')),
                ('security_comment', models.TextField(blank=True, verbose_name='ملاحظات الأمن')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ التقديم')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visit_requests', to='entities.entity', verbose_name='الجهة')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visit_requests', to=settings.AUTH_USER_MODEL, verbose_name='طالب الزيارة')),
            ],
            options={
                'verbose_name': 'طلب زيارة',
                'verbose_name_plural': 'طلبات الزيارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_time', models.TimeField(verbose_name='الوقت المحجوز')),
                ('status', models.CharField(choices=[('pending', 'بانتظار التأكيد'), ('confirmed', 'مؤكد'), ('cancelled', 'ملغي'), ('completed', 'مكتمل'), ('no_show', 'لم يحضر')], default='pending', max_length=20, verbose_name='الحالة')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الحضور')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='visits.visitschedule', verbose_name='الجدول')),
                ('visit_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='visits.visitrequest', verbose_name='طلب الزيارة')),
            ],
            options={
                'verbose_name': 'حجز موعد',
                'verbose_name_plural': 'حجوزات المواعيد',
                'ordering': ['schedule__date', 'requested_time'],
            },
        ),
        migrations.AddIndex(
            model_name='visitrequest',
            index=models.Index(fields=['status', 'requested_date'], name='visits_visi_status_38bf9f_idx'),
        ),
        migrations.AddIndex(
            model_name='visitrequest',
            index=models.Index(fields=['visit_type', 'status'], name='visits_visi_visit_t_c74d0d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='visitbooking',
            unique_together={('schedule', 'requested_time', 'status')},
        ),
    ]
