# Generated by Django 4.2.11 on 2025-12-22 21:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='اسم الجهة')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='رمز الجهة')),
                ('level', models.CharField(choices=[('vice_rectorate', 'وكالة/قطاع'), ('college_deanship', 'كلية/عمادة'), ('department_unit', 'قسم/وحدة')], default='department_unit', max_length=20, verbose_name='المستوى الهرمي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='الجهة الأعلى في الهيكل الهرمي', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='entities.entity', verbose_name='الجهة الأم')),
            ],
            options={
                'verbose_name': 'جهة',
                'verbose_name_plural': 'الجهات',
                'ordering': ['level', 'name'],
                'indexes': [models.Index(fields=['level', 'is_active'], name='entities_en_level_b28b7c_idx'), models.Index(fields=['parent'], name='entities_en_parent__2d39a1_idx')],
            },
        ),
    ]
