# Generated by Django 4.2.16 on 2025-11-10 16:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='اسم الخدمة')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True, verbose_name='المُعرف')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('icon', models.CharField(blank=True, max_length=10, verbose_name='الأيقونة')),
                ('category', models.CharField(choices=[('documents', 'المستندات الرسمية'), ('design', 'التصميم والإبداع'), ('marketing', 'الترويج والفعاليات'), ('medical', 'الخدمات الطبية'), ('general', 'خدمات عامة')], default='general', max_length=32, verbose_name='التصنيف')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعلة')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='يتطلب اعتماد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'خدمة',
                'verbose_name_plural': 'الخدمات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=120, verbose_name='المفتاح البرمجي')),
                ('label', models.CharField(max_length=200, verbose_name='العنوان الظاهر')),
                ('field_type', models.CharField(choices=[('text', 'نص'), ('number', 'عدد'), ('radio', 'اختيار واحد'), ('textarea', 'نص متعدد'), ('file', 'ملف'), ('link', 'رابط')], default='text', max_length=20, verbose_name='نوع الحقل')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='الترتيب')),
                ('is_required', models.BooleanField(default=False, verbose_name='إلزامي')),
                ('is_visible', models.BooleanField(default=True, verbose_name='ظاهر')),
                ('placeholder', models.CharField(blank=True, max_length=255, verbose_name='نص إرشادي')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='وصف مختصر')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='إعدادات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='catalog.service', verbose_name='الخدمة')),
            ],
            options={
                'verbose_name': 'حقل خدمة',
                'verbose_name_plural': 'حقول الخدمات',
                'ordering': ['service', 'order'],
                'unique_together': {('service', 'key')},
            },
        ),
        migrations.CreateModel(
            name='ServicePricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('internal_cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='التكلفة الداخلية')),
                ('external_cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='تكلفة السوق')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='ملاحظات')),
                ('effective_from', models.DateField(blank=True, null=True, verbose_name='تاريخ السريان')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='catalog.service', verbose_name='الخدمة')),
            ],
            options={
                'verbose_name': 'تسعيرة خدمة',
                'verbose_name_plural': 'تسعيرات الخدمات',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFieldOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=150, verbose_name='الخيار')),
                ('value', models.CharField(max_length=150, verbose_name='القيمة البرمجية')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='الترتيب')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalog.servicefield', verbose_name='الحقل')),
            ],
            options={
                'verbose_name': 'خيار حقل',
                'verbose_name_plural': 'خيارات الحقول',
                'ordering': ['field', 'order'],
                'unique_together': {('field', 'value')},
            },
        ),
    ]
