# Generated by Django 4.2.11 on 2025-12-22 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='entity',
            field=models.ForeignKey(blank=True, help_text='الجهة التابعة لها المستخدم (يُحدد من Active Directory)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='entities.entity', verbose_name='الجهة'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('consumer', 'مستهلك'), ('print_manager', 'مدير المطبعة'), ('dept_manager', 'مدير القسم'), ('dept_employee', 'موظف القسم'), ('training_supervisor', 'مشرف التدريب'), ('inventory', 'مراقب مخزون'), ('admin', 'مدير النظام'), ('approver', 'معتمد'), ('staff', 'موظف المطبعة'), ('requester', 'مستخدم')], default='consumer', max_length=32, verbose_name='الدور'),
        ),
    ]
