# Generated by Django 4.2.16 on 2025-11-10 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_updates', models.BooleanField(default=True)),
                ('approvals', models.BooleanField(default=True)),
                ('inventory_alerts', models.BooleanField(default=False)),
                ('weekly_digest', models.BooleanField(default=True)),
                ('email_subscription', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تفضيلات الإشعارات',
                'verbose_name_plural': 'تفضيلات الإشعارات',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('type', models.CharField(choices=[('order_status', 'تحديث حالة الطلب'), ('approval', 'قرار اعتماد'), ('inventory_alert', 'تنبيه مخزون'), ('system', 'إشعار نظامي')], max_length=30, verbose_name='النوع')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('is_read', models.BooleanField(default=False, verbose_name='تمت القراءة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ القراءة')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المتلقي')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
    ]
