# Generated by Django 4.2.11 on 2025-12-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('order_status', 'تحديث حالة الطلب'), ('approval', 'قرار اعتماد'), ('inventory_alert', 'تنبيه مخزون'), ('system', 'إشعار نظامي'), ('deadline_warning', 'تحذير انتهاء مهلة'), ('ready_for_delivery', 'جاهز للتسليم'), ('inventory_low', 'انخفاض المخزون')], max_length=30, verbose_name='النوع'),
        ),
    ]
