# Generated by Django 4.2.11 on 2025-12-22 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trainee_name', models.CharField(max_length=255, verbose_name='اسم المتدرب')),
                ('trainee_id', models.CharField(max_length=50, verbose_name='رقم الهوية/الجامعي')),
                ('trainee_phone', models.CharField(max_length=25, verbose_name='رقم الجوال')),
                ('trainee_email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('university', models.CharField(max_length=255, verbose_name='الجامعة/المؤسسة')),
                ('major', models.CharField(max_length=255, verbose_name='التخصص')),
                ('training_period_start', models.DateField(verbose_name='بداية فترة التدريب')),
                ('training_period_end', models.DateField(verbose_name='نهاية فترة التدريب')),
                ('department', models.CharField(help_text='قسم التصميم، قسم الطباعة، إلخ', max_length=100, verbose_name='القسم المطلوب')),
                ('purpose', models.TextField(verbose_name='الغرض من التدريب')),
                ('status', models.CharField(choices=[('pending', 'بانتظار المراجعة'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('supervisor_comment', models.TextField(blank=True, verbose_name='ملاحظات المشرف')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ التقديم')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='training_requests', to='entities.entity', verbose_name='الجهة')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_requests', to=settings.AUTH_USER_MODEL, verbose_name='طالب التدريب')),
                ('supervisor', models.ForeignKey(blank=True, limit_choices_to={'role': 'training_supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_trainings', to=settings.AUTH_USER_MODEL, verbose_name='مشرف التدريب')),
            ],
            options={
                'verbose_name': 'طلب تدريب',
                'verbose_name_plural': 'طلبات التدريب',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evaluation_type', models.CharField(choices=[('weekly', 'تقييم أسبوعي'), ('final', 'تقييم نهائي')], max_length=20, verbose_name='نوع التقييم')),
                ('week_number', models.PositiveIntegerField(blank=True, help_text='للتقييم الأسبوعي فقط', null=True, verbose_name='رقم الأسبوع')),
                ('attendance_score', models.PositiveIntegerField(default=0, help_text='من 0 إلى 100', verbose_name='درجة الحضور')),
                ('performance_score', models.PositiveIntegerField(default=0, help_text='من 0 إلى 100', verbose_name='درجة الأداء')),
                ('behavior_score', models.PositiveIntegerField(default=0, help_text='من 0 إلى 100', verbose_name='درجة السلوك')),
                ('comments', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('evaluated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ التقييم')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='المقيّم')),
                ('training_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='training.trainingrequest', verbose_name='طلب التدريب')),
            ],
            options={
                'verbose_name': 'تقييم تدريب',
                'verbose_name_plural': 'تقييمات التدريب',
                'ordering': ['-evaluated_at'],
                'unique_together': {('training_request', 'evaluation_type', 'week_number')},
            },
        ),
    ]
