# Generated by Django 4.2.16 on 2025-11-10 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='اسم المادة')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='رمز المخزون')),
                ('category', models.CharField(choices=[('paper', 'ورق'), ('ink', 'أحبار'), ('banner', 'بنرات'), ('other', 'مستهلكات أخرى')], default='other', max_length=20, verbose_name='التصنيف')),
                ('unit', models.CharField(default='قطعة', max_length=20, verbose_name='وحدة القياس')),
                ('current_quantity', models.PositiveIntegerField(default=0, verbose_name='الكمية الحالية')),
                ('minimum_threshold', models.PositiveIntegerField(default=0, verbose_name='الحد الأدنى')),
                ('maximum_threshold', models.PositiveIntegerField(default=1000, verbose_name='الحد الأعلى')),
                ('reorder_point', models.PositiveIntegerField(default=0, verbose_name='نقطة إعادة الطلب')),
                ('last_restocked_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر تزويد')),
                ('last_usage_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر استهلاك')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مادة مخزون',
                'verbose_name_plural': 'مواد المخزون',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReorderRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية المطلوبة')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('ordered', 'تم الطلب'), ('received', 'تم الاستلام'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الطلب')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاستلام')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_approvals', to=settings.AUTH_USER_MODEL, verbose_name='المعتمد')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_requests', to='inventory.inventoryitem', verbose_name='المادة')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_requests', to=settings.AUTH_USER_MODEL, verbose_name='طالب التزويد')),
            ],
            options={
                'verbose_name': 'طلب تزويد مخزون',
                'verbose_name_plural': 'طلبات التزويد',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(choices=[('in', 'إضافة'), ('out', 'صرف'), ('adjust', 'تعديل')], max_length=10, verbose_name='العملية')),
                ('quantity', models.IntegerField(verbose_name='الكمية')),
                ('balance_after', models.IntegerField(verbose_name='الرصيد بعد العملية')),
                ('reference_order', models.CharField(blank=True, max_length=50, verbose_name='رقم الطلب المرجعي')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='ملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='inventory.inventoryitem', verbose_name='المادة')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل مخزون',
                'verbose_name_plural': 'سجلات المخزون',
                'ordering': ['-created_at'],
            },
        ),
    ]
