# Generated by Django 4.2.11 on 2025-12-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='min_quantity',
            field=models.PositiveIntegerField(default=0, help_text='عند وصول الكمية إلى هذا الحد، يتم إرسال تنبيه لمدير المطبعة', verbose_name='الحد الأدنى للتنبيه'),
        ),
    ]
