# Generated by Django 4.2.11 on 2025-12-22 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_printorder_printattachment_designorder_and_more'),
        ('inventory', '0002_inventoryitem_min_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylog',
            name='print_order',
            field=models.ForeignKey(blank=True, help_text='طلب الطباعة المرتبط بهذا الخصم', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_logs', to='orders.printorder', verbose_name='طلب الطباعة'),
        ),
    ]
